/*
What is Hydration in React / Next.js?

Hydration is the process where React takes the HTML already generated by the server and attaches JavaScript behavior to it on the browser.
In simple terms: Server generates HTML → Browser displays it → React hydrates it → HTML becomes interactive.

Example

Suppose Next.js renders:

<button onClick={handleClick}>
  Count: {count}
</button>

The server sends HTML like: <button>Count: 0</button>

The browser can immediately display the button. Then React loads the JavaScript and hydrates that HTML by attaching the onClick handler.

What is a Hydration Error?

A hydration error happens when: The HTML generated on the server doesn't match what React expects to render on the client.

How do we solve hydration errors?
First I identify the difference between the server-rendered HTML and the initial client render. I make sure the initial render is deterministic and produces the same markup on both sides. Browser-only APIs such as window and localStorage are accessed inside useEffect or a client component. Dynamic values such as Date and Math.random are avoided during rendering or generated after hydration. If a component is completely client-only, I can also use dynamic import with SSR disabled when appropriate.
*/

export default function Page() {
  return (
    <div>
      Current time: {new Date().toLocaleTimeString()}
    </div>
  );
}

"use client";

import { useEffect, useState } from "react";

export default function Time() {
  const [time, setTime] = useState("");

  useEffect(() => {
    setTime(new Date().toLocaleString());
  }, []);

  return <div>{time || "Loading..."}</div>;
}
